### ISSUE TITLE
Issue while querying Routing API - incorrect received route

### ISSUE THREAD

**Issue by carlos-mg89** [graphhopper/directions-api#84]
I've been trying to figure out what's wrong with this query and the surrounding paths in OpenStreetMap, but haven't really got anything clear.

This is the route I'm trying to plan either using the Routing API from www.graphhopper.com or using the planning on OpenStreetMap with the Graphhopper option enabled ( https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=42.6810%2C0.0264%3B42.6754%2C0.0345#map=15/42.6773/0.0332 )

As you can observe, the planned route should have been quite straight (I have walked it myself a couple of weeks ago). But it does a huge turn, going through a path that's actually quite dangerous and not feasible for everybody.

I checked the area on OpenStreetMap with the online edit tool, but haven't seen that any of the paths are disconnected.

Normally I get logic routes, and whenever I've got wrong tracks, when checking Open Street Map I've seen broken paths.

Any ideas?

**Comment by karussell** [comment]
Please avoid issues if you have a question and use our forum.

The problem is this way https://www.openstreetmap.org/way/140319953 that has "demanding_alpine_hiking" as sac_scale and we do not allow this for foot, but we allow this for "[hike](https://graphhopper.com/maps/?point=42.676078%2C0.033646&point=42.680416%2C0.026608&vehicle=hike&layer=TF%20Outdoors)" - an option only available on GH Maps.

**Comment by carlos-mg89** [comment]
@karussell thanks for your help, now I can understand what was going on.

I'll remember where to post this kind of questions.
